Repository EthanCharpentier667/Wolf3D-action, pull requests merged in 2025-05, with the labels that each got.

#85 feat (raycasting - environment): you can know add obstacles wall and …
  Create/environment.c
  Makefile
  includes/environnement.h
  includes/frame.h
  includes/inititliser.c
  src/assets/wall.png
  src/assets/wall2.png
  src/assets/wall3.png
  src/assets/wall4.png
  src/init/init_game.c
  src/raycast/drawer.c
  src/raycast/raycasting.c
Labels: enhancement

#86 Flashlight feature
  Create/environment.c
  Makefile
  includes/frame.h
  src/init/init_game.c
  src/init/init_player.c
  src/raycast/drawer.c
  src/raycast/flashlight.c
  src/raycast/ray_cast_floor_and_ceiling.c
  src/raycast/raycasting.c
  src/scenes/game.c
Labels: bug, enhancement

#87 fix (raycsting): you can know render walls with rec textures and item…
  Create/window.c
  Frame/handle_event.c
  Makefile
  includes/frame.h
  includes/inititliser.c
  src/assets/door.png
  src/enemy/pathfinding.c
  src/init/init.c
  src/init/init_doors.c
  src/player/move.c
  src/raycast/drawer.c
  src/raycast/enemy.c
  src/raycast/item.c
  src/raycast/obstacle.c
  src/raycast/raycasting.c
  src/raycast/update_door.c
  src/scenes/game.c
Labels: bug, enhancement

#88 Weapons
  Create/weapon.c
  Makefile
  includes/frame.h
  includes/inititliser.c
  includes/weapon.h
  src/assets/knife.png
  src/init/init_game.c
  src/player/cam.c
  src/raycast/draw_hud.c
  src/scenes/game.c
  src/weapon/find_enemy_in_range.c
  src/weapon/update_weapon.c
Labels: enhancement

#89 fix (initalisation): now init functions return boolean
  Frame/sliders_events.c
  Makefile
  includes/frame.h
  main.c
  src/init/init.c
  src/init/init_ambiant.c
  src/init/init_doors.c
  src/init/init_game.c
  src/init/init_minimap.c
  src/init/init_player.c
  src/init/init_settings.c
  src/init/init_ui.c
  src/inventory/init_inventory.c
Labels: invalid

#90 feat (settings): adding a keybinding system + all the setting menu
  Frame/buttons_events.c
  Frame/handle_event.c
  Frame/inventory_events.c
  Makefile
  includes/button.h
  includes/frame.h
  includes/inititliser.c
  includes/keyname.h
  src/actions/keybinds.c
  src/actions/resolution.c
  src/actions/settings.c
  src/assets/audio.png
  src/assets/controls.png
  src/assets/keybind.png
  src/assets/resadd.png
  src/assets/resolution.png
  src/assets/ressub.png
  src/init/init_settings.c
  src/player/move.c
  src/raycast/enemy.c
  src/raycast/healthbar.c
  src/raycast/item.c
  src/scenes/scenes_manager.c
  src/scenes/settings.c
Labels: enhancement

#92 Life
  Create/enemy.c
  Create/hud.c
  Create/window.c
  Makefile
  includes/enemies.h
  includes/frame.h
  includes/inititliser.c
  src/assets/Blood_Overlay.png
  src/enemy/damage_player.c
  src/enemy/pathfinding.c
  src/enemy/update_ennemies.c
  src/init/init_game.c
  src/init/init_player.c
  src/raycast/draw_hud.c
  src/raycast/enemy.c
Labels: enhancement

#93 feat (NON-billboard Object): you can now create objects fix on the ma…
  Create/fixed_objects.c
  Makefile
  includes/fixed_object.h
  includes/frame.h
  includes/inititliser.c
  src/assets/door.png
  src/init/init.c
  src/init/init_doors.c
  src/init/init_game.c
  src/init/init_objects.c
  src/raycast/enemy.c
  src/raycast/fixed_object.c
  src/raycast/item.c
  src/raycast/raycasting.c
  src/raycast/update_door.c
  src/scenes/game.c
Labels: enhancement

#94 Bugs - Ennemies with doors
  src/assets/heal.png
  src/raycast/enemy.c
Labels: bug

#95 feat (draw - objects): all objects are now draw by distance
  includes/frame.h
  src/scenes/game.c
Labels: enhancement

#96 feat (heal system & usable items): door have to be open with keys. He…
  includes/frame.h
  includes/inititliser.c
  src/init/init_game.c
  src/init/init_objects.c
  src/inventory/draw_item_details.c
  src/inventory/inventory_actions.c
  src/raycast/update_door.c
Labels: enhancement

#97 feat (ennemies - drop): you can now in parameters give an item name a…
  Create/item.c
  includes/enemies.h
  includes/frame.h
  includes/inititliser.c
  src/enemy/update_ennemies.c
  src/init/init_game.c
  src/inventory/inventory_actions.c
  src/raycast/fixed_object.c
  src/weapon/update_weapon.c
Labels: enhancement

#98 Weapons
  Create/fixed_objects.c
  Create/weapon.c
  Makefile
  includes/frame.h
  includes/inititliser.c
  includes/weapon.h
  src/assets/Machine_Gun_Ajustement.png
  src/assets/Machine_Gun_Tir.png
  src/init/init_game.c
  src/init/init_objects.c
  src/init/init_ui.c
  src/raycast/draw_hud.c
  src/raycast/fixed_object.c
  src/weapon/find_enemy_in_range.c
  src/weapon/knife_behavior.c
  src/weapon/machine_gun.c
  src/weapon/reload_weapons.c
  src/weapon/switch_weapons.c
  src/weapon/update_weapon.c
Labels: enhancement

#100 fix (load): load frame splitted up in sub files and coding-styled
  Makefile
  includes/frame.h
  src/game/load_enemies_data.c
  src/game/load_frame.c
  src/game/load_inventory_data.c
  src/game/load_items_data.c
  src/game/load_map_data.c
  src/game/load_objects_data.c
Labels: bug

#101 Sprint
  includes/frame.h
  src/player/move.c
  src/raycast/raycasting.c
Labels: enhancement

#104 feat (enemies): add a new enemy to the game
  includes/inititliser.c
  src/assets/enemy2.png
Labels: enhancement

#105 feat (weapon_sound): animation of weapons now have sound linked
  Makefile
  includes/frame.h
  includes/weapon.h
  src/assets/knife_slash.wav
  src/assets/shot_mg.wav
  src/assets/windup_mg.wav
  src/weapon/knife_behavior.c
  src/weapon/machine_gun.c
  src/weapon/weapon_sounds.c
Labels: enhancement

#107 feat (ennemies): adding the boss enemies with 2 phases
  Create/clocks.c
  Makefile
  includes/enemies.h
  includes/frame.h
  includes/inititliser.c
  src/assets/Hitler.png
  src/assets/Hitler1.png
  src/enemy/basic_enemy.c
  src/enemy/hitler_enemy.c
  src/enemy/pathfinding.c
  src/enemy/update_ennemies.c
  src/init/init.c
  src/init/init_game.c
  src/raycast/enemy.c
  src/raycast/healthbar.c
  src/vfx/draw_vfx.c
  sswolfs/save-EthanLeGrand.png
  sswolfs/save-EthanLeGrand.ww2
Labels: enhancement

#109 fix (ennemy): add a follow range to ennemy fix FOV of enemy to attack…
  Frame/sliders_events.c
  Makefile
  includes/enemies.h
  includes/frame.h
  includes/inititliser.c
  includes/slider.h
  src/actions/sliders.c
  src/enemy/hitler_enemy.c
  src/enemy/pathfinding.c
  src/enemy/update_ennemies.c
  src/game/load_enemies_data.c
  src/game/load_frame.c
  src/game/timer.c
  src/init/init_game.c
  src/inventory/inventory.c
  src/inventory/inventory_actions.c
  src/raycast/update_door.c
  src/scenes/game.c
  sswolfs/save-EthanLeGrand.png
  sswolfs/save-EthanLeGrand.ww2
Labels: enhancement

#111 feat (heal - item): added a new image to the item 'heal' now size is …
  includes/inititliser.c
  src/assets/gameover.png
  src/assets/heal.png
  src/assets/victory.png
Labels: enhancement

#112 Sfx addons
  src/assets/gun.png
  src/assets/terminator.png
  src/assets/white_enemy.png
  src/player/cam.c
Labels: enhancement

#120 feat (weather): adding windows system that change every 100 scd for reprocduce a weather climat
  Makefile
  includes/frame.h
  includes/inititliser.c
  src/assets/window.png
  src/assets/window2.png
  src/assets/window3.png
  src/assets/window4.png
  src/game/update_windows.c
  src/init/init_objects.c
  src/scenes/game.c
Labels: enhancement

#122 windows decoration
  includes/inititliser.c
  src/assets/enemy_blu.png
  src/assets/enemy_white.png
  src/game/update_windows.c
Labels: enhancement
